# Generated by Django 2.0.3 on 2018-05-26 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Point_Balance', models.CharField(default=0.0, max_length=30)),
                ('Cash_Balance', models.CharField(default=0.0, max_length=30)),
                ('User_Type', models.CharField(choices=[('Free', 'Free'), ('Starter', 'Starter'), ('Business', 'Business'), ('Professional', 'Professional')], default='Free', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
