# Generated by Django 2.0.3 on 2018-06-04 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Talla_Global_Home', '0003_auto_20180604_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Phone_Number',
        ),
    ]
