# Generated by Django 2.0.3 on 2018-06-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Talla_Global_Home', '0004_remove_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Phone_Number',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
